### ISSUE TITLE
Fix Jinja support to allow for iteration over metadata

### ISSUE THREAD

**Issue by Lukas-Dresel** [rhelmot/pydatatask#22]
E.g. for dynamic tool you might want things like this:
```bash
export {% for await k, v in runtime_config.env.items() %}{{k}}={{v}}{% endfor %}
```

At the moment, this causes pydatatask to throw the following error ```
ERROR:pydatatask.pipeline:Failed to launch fuzz_symcts:1
Traceback (most recent call last):
  File "/home/Lukas-Dresel/lukas/aixcc/pydatatask/pydatatask/pipeline.py", line 243, in worker
    await self.tasks[task].launch(job)
  File "/home/Lukas-Dresel/lukas/aixcc/pydatatask/pydatatask/task.py", line 1715, in launch
    exe_txt = await render_template(self.template, env)
  File "/home/Lukas-Dresel/lukas/aixcc/pydatatask/pydatatask/task.py", line 117, in render_template
    templating = j.from_string(template_str)
  File "/home/Lukas-Dresel/.virtualenvs/aixcc/lib/python3.8/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/Lukas-Dresel/.virtualenvs/aixcc/lib/python3.8/site-packages/jinja2/environment.py", line 766, in compile
    return self._compile(source, filename)
  File "/home/Lukas-Dresel/.virtualenvs/aixcc/lib/python3.8/site-packages/jinja2/environment.py", line 704, in _compile
    return compile(source, filename, "exec")  # type: ignore
  File "<template>", line 43
SyntaxError: cannot assign to await expression
```

We should find some way to make this possible as we'll almost certainly need it at least to pass around runtime configuration values (env variables, args, etc.)

**Comment by Lukas-Dresel** [comment]
For now i've worked around it via just passing strings, but this would be a nice feature to have regardless. E.g. a `nproc` could spawn `nproc` instances, etc.

**Comment by Lukas-Dresel** [comment]
Another thing to consider for the future: targets will need as part of their runtime config certain files to be present, they should also be passable via this setting somehow.
